substitutions:
  name: esphome-web-e9f624
  friendly_name: Xiaozhi Taichi Pi v1

## Modular version Main v1.02
## Split up the original yaml for easier maintance of many devices with different hardware.

## SETTINGS ######################################################################################################################################
  imagewidth:  "360"
  imageheight: "360"
  rotate_display: "180"

  startup_sound: "Home_Connected" # (options are: available, Home_Connected, Home_Connected_Male, Computer_Ready)
  clock_background_image: "clock" # (options are: clock, hacker, ha-girl, mission, starrysky)
  imagemodel: "Gwen" # options are:

# Alita, Alfred, Astrobot, Buzz, Casita, Cybergirl, Dory, EVE, Eyes, Eyes2, GLaDOS, Girl1, Guy1, Guy2, Gwen, HA-character, ha-girl, Hacker, Harley,
# Jarvis, Luffy, Mario, Max, Prime, Robochibi, Robocop, Robot, Robotgirl, Shaun
##################################################################################################################################################

  font_glyphsets: "GF_Latin_Core"
  font_family: Figtree

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"

psram:
  mode: octal
  speed: 80MHz

packages:
  core:
    url: https://github.com/RealDeco/xiaozhi-esphome.git
    ref: main
    refresh: 1d
    files:
      - devices/Under_Development/Modular/core.yaml
  hw:
    url: https://github.com/RealDeco/xiaozhi-esphome.git
    ref: main
    refresh: 1d
    files:
      - devices/Under_Development/Modular/HW/guition_180v1_hw.yaml

## ENABLE / DISABLE WAKE WORDS ## IF LOW ON MEMORY, USE LESS WAKE WORDS ##########################################################################
micro_wake_word:
  id: mww
  models:
    - hey_jarvis
    - alexa
#    - hey_mycroft
#    - model: "https://raw.githubusercontent.com/esphome/micro-wake-word-models/refs/heads/main/models/v2/experiments/choo_choo_homie.json"
#    - model: "https://raw.githubusercontent.com/esphome/micro-wake-word-models/refs/heads/main/models/v2/experiments/hey_home_assistant.json"
#    - model: "https://raw.githubusercontent.com/esphome/micro-wake-word-models/refs/heads/main/models/v2/experiments/hey_peppa_pig.json"
#    - model: "https://raw.githubusercontent.com/esphome/micro-wake-word-models/refs/heads/main/models/v2/experiments/okay_computer.json"
##################################################################################################################################################
